### ISSUE TITLE
Does not play, only buffering

### ISSUE THREAD

**Issue by agencia3w** [dehy/react-native-radio-player#4]
I used the sample file https://github.com/dehy/react-native-radio-player/blob/master/example/src/App.tsx

**Comment by dehy** [comment]
Can you give me the URL you try to listen to?

**Comment by alinrzv** [comment]
Same here , this project is dead , also cannot be used with Flow .... cancell it or update it ..

**Comment by dehy** [comment]
> Same here , this project is dead , also cannot be used with Flow .... cancell it or update it ..

This is a free open-source project done on my spare time. Feel free to give me more information to look into. You're also welcome to submit a PR to fix this problem.

**Comment by alinrzv** [comment]
Pick any of the stream here and try it !
https://astreaming.edi.ro:8443

**Comment by alinrzv** [comment]
Here video screen recording for https://astreaming.edi.ro:8443/EuropaFM_aac

https://drive.google.com/file/d/1CT5-8TTGOOipEHfhn8NJTshxOB-KbI3G/view?usp=sharing

**Comment by dehy** [comment]
> Here video screen recording for https://astreaming.edi.ro:8443/EuropaFM_aac
> 
> https://drive.google.com/file/d/1CT5-8TTGOOipEHfhn8NJTshxOB-KbI3G/view?usp=sharing

So, there 1 bug I think I cannot do something for now, and 1 I will fix soon.

## TLS Certificate Verification Failure

The first and main bug is a TLS certificate problem from your server or from Android. There is an explicit error in the Android Studio logs: `Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`
It seems android cannot validate the https certificate. I don't know if I can handle this specifically. It needs more research.

**Workaround** : use your plain http link : http://astreaming.edi.ro:8000/EuropaFM_aac

## Metadata parsing

When using the plain http link, the app crash due to a bad handling of the stream metadatas. I will fix this and one day, make a parameter that permit to specify the artist/title string separator. It's actually hardcoded as ` - ` (with spaces around) but your stream uses `/`.

**Comment by dehy** [comment]
@alinrzv [Release 0.2.3](https://github.com/dehy/react-native-radio-player/releases/tag/v0.2.3) is now available, fixing the metadata character crash.

**Comment by alinrzv** [comment]
Hi @dehy , well .. is strange , is not my server though , is a public streaming server for Romanian radio stations , it seems that in the browser the ssl is valid , but not valid in all browsers , the server it seems that is missing some intermediate.crt , this might be the case for other icecast servers as well , thanks for looking into it ! 

As for the certificate issue i guess there are some overriding options but wont fit within the app default structure , users can bypass that via android:networkSecurityConfig throughAndroid Manifest xml ...

I will test the package later , i want to write some custom radio stations app, so i'm looking for any app that can help me with the streams , this one having meta as well , seems good !

Thanks a bunch !

**Comment by agencia3w** [comment]
> Can you give me the URL you try to listen to?

http://directradios.net:8310/listen.pls?sid=1

**Comment by dehy** [comment]
> > Can you give me the URL you try to listen to?
> 
> http://directradios.net:8310/listen.pls?sid=1

You're trying to play a "playlist" (ˋ.pls` file format) and not a stream directly. 

Inside this text file you can open with a text editor, there is the real stream url: http://directradios.net:8310/stream

Try this one
